name: "Windows inside a docker image"
description: "Windows inside a docker image"
version: "5.02.1"
slug: "hello_world"
init: false
arch:
  - amd64
ports:
  8006/tcp: 8006
  8006/udp: 8006
  3389/tcp: 3389
  3389/udp: 3389
